### ISSUE TITLE
Can't query using `$nearSphere` because of model validation of query object

### ISSUE THREAD

**Issue by simonschllng** [RideAmigosCorp/mongoose-geojson-schema#15]
Not sure if this is related to #13.

My schema is: 

````
const MySchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  points: [mongoose.Schema.Types.Feature]
});
MySchema.index({ 'points.geometry': '2dsphere' });
````

I can query it in mogodb:

````
db.myCollection.find({"points.geometry": {$nearSphere: {$geometry: {type: "Point", coordinates: [8.66, 50.10] }}}})
````

Querying it with mongoose throws an error.

````
      query.points = {
        geometry: {
          $nearSphere: {
            $geometry: {
              type: 'Point',
              coordinates: [lon, lat]
            }
          }
        }
      };

    return this.find(query) // ...
````

→ **Error: Feature must have a type**

I can work around all the validation errors by adding missing properties to the query:

````
      query.points = {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [1, 1],
          $nearSphere: {
            $geometry: {
              type: 'Point',
              coordinates: [lon, lat]
            }
          }
        }
      };

    return this.find(query) // ...
````

But this, of course, does not return any results as long as I don't have a point at `[1, 1]`.

How should I query in this case?

**Comment by markstos** [comment]
It looks like perhaps you have declared in your schema that `points` is to be an array of Features:

> points: [mongoose.Schema.Types.Feature]

But then you are treating it like it is a single feature. For example, expect `points` to have an geometry property:

> MySchema.index({ 'points.geometry': '2dsphere' });

Also, I think `$nearSphere` is meant to work on a single GeoJSON element, not an array of them.

**Comment by joshkopecek** [comment]
Correct @markstos - Mongo will only deal with indexing a GeoJSON object in a document in a collection, not an array. I don't know what you'd be expecting the result to be if you had e.g. an array of Points.
