### ISSUE TITLE
Add "schemaName" to each of the SchemaTypes

### ISSUE THREAD

**Issue by GerardSoleCa** [RideAmigosCorp/mongoose-geojson-schema#16]
Hi,

We are currently using your awesome library in a project, and we use another library to convert models into JsonSchemas.

I've seen that this library lacks of the schemaName of each SchemaType, which is required for conversion.

In fact, you can see that mongoose schemas implement this property [string.js](https://github.com/Automattic/mongoose/blob/4.8.5/lib/schema/string.js#L32), [date.js](https://github.com/Automattic/mongoose/blob/4.8.5/lib/schema/date.js#L31)

I'll be doing a pull request in some minutes, and if you like it, I would really appreciate a merge :)

Thanks!

**Comment by joshkopecek** [comment]
Closed and merged PR.
