### ISSUE TITLE
Adding properties gives error while persisting the JSON with Feature object

### ISSUE THREAD

**Issue by himanshu810e** [RideAmigosCorp/mongoose-geojson-schema#6]
The object I am trying to persist :
{ rating:
   { type: 'Feature',
     geometry: { coordinates: [Object], type: 'Point' },
     properties: { Typ: 'Velo', currentRating: '2' } },
  created_at: Thu Dec 10 2015 19:14:28 GMT+0100 (W. Europe Standard Time),
  updated_at: Thu Dec 10 2015 19:14:28 GMT+0100 (W. Europe Standard Time),
  _id: 5669c104018a6b5c1009d4c1,
  htmlverified: 'Nope (Thanks for spamming my map...)',
  location: [ 4.482, 27.372 ],
  favlang: 'asda sd',
  age: 99,
  gender: 'What\'s it to ya?',
  username: 'asdad' }

The error I recieve:

{ [MongoError: Can't extract geo keys: { _id: ObjectId('5669c104018a6b5c1009d4c1'), username: "asdad", gender: "What's it to ya?", age: 99, favlang: "asda sd", location: [ 4.482, 27.372 ], htmlverified: "Nope (Thanks for spamming my map...)", updated_at: new Date(1449771268368), created_at: new Date
(1449771268329), rating: { properties: { currentRating: "2", Typ: "Velo" }, geometry: { type: "Point", coordinates: [ "4.482", "27.372" ] }, type: "Feature" }, __v: 0 }  unknown GeoJSON type: { properties: { currentRating: "2", Typ: "Velo" }, geometry: { type: "Point", coordinates: [ "4.482", "27.37
2" ] }, type: "Feature" }]
  name: 'MongoError',
  message: 'Can\'t extract geo keys: { _id: ObjectId(\'5669c104018a6b5c1009d4c1\'), username: "asdad", gender: "What\'s it to ya?", age: 99, favlang: "asda sd", location: [ 4.482, 27.372 ], htmlverified: "Nope (Thanks for spamming my map...)", updated_at: new Date(1449771268368), created_at: new Dat
e(1449771268329), rating: { properties: { currentRating: "2", Typ: "Velo" }, geometry: { type: "Point", coordinates: [ "4.482", "27.372" ] }, type: "Feature" }, __v: 0 }  unknown GeoJSON type: { properties: { currentRating: "2", Typ: "Velo" }, geometry: { type: "Point", coordinates: [ "4.482", "27.3
72" ] }, type: "Feature" }',
  driver: true,
  code: 16755,

My mongoose Schema:

var UserSchema = new mongoose.Schema({
    rating:GeoJSON.Feature,
    username: {type: String, required: true},
    gender: {type: String, required: true},
    age: {type: Number, required: true},
    favlang: {type: String, required: true},
    location: {type: [Number], required: true}, // [Long, Lat]
    htmlverified: String,
    created_at: {type: Date, default: Date.now},
    updated_at: {type: Date, default: Date.now}
	 
});

**Comment by markstos** [comment]
Retry with the new 1.0.0 release. Note that the syntax has changed.  The new release offers stronger GeoJSON schema validation, which may help here. 

However, there is a known issue that you may now get a generic "failure to cast" message  instead of a more helpful message about exactly /why/ something failed validation. Improving the diagnostics is a TODO. 

Re-open if you still see a problem with the 1.0 release.
