### ISSUE TITLE
specific errors are not available when validation fails

### ISSUE THREAD

**Issue by markstos** [RideAmigosCorp/mongoose-geojson-schema#8]
This issue is explained upstream: https://github.com/Automattic/mongoose/issues/4113

@joshkopecek Would you mind testing a code update that throws a different type of error besides `CastError` to see if that exposes the raw error messages?  

Maybe a [MongooseError](http://mongoosejs.com/docs/api.html#error_MongooseError) ?

**Comment by joshkopecek** [comment]
Pushed a change which throws `mongoose.Error` for each problem. It now tests for specific strings in the error reasons. We'll wait for CastError to be modified in the Mongoose repo then we can use a proper CastError, but this will do for the meantime.
