### ISSUE TITLE
GeoJSON type

### ISSUE THREAD

**Issue by joshkopecek** [RideAmigosCorp/mongoose-geojson-schema#9]
I've just realised something quite obvious:
If we instead used `mongoose.SchemaTypes.GeoJSON` and did all the validation using the `type` parameter we'd avoid polluting the SchemaTypes object with all the separate GeoJSON types. What do you think @markstos ?

**Comment by markstos** [comment]
I see what you mean. I'm not sure what risk there is of collisions now, but certainly using GeoJSON as the top-level Schema element would be very-low risk.

If you wanted to go ahead and refactor a 2.0 release soon, I doubt many people have had a chance to adopt the 1.0.x syntax. 

As long the amount of syntax people need is similar and we get clear diagnostic messages, I'm in favor of the change.

**Comment by joshkopecek** [comment]
Yes, I'll see what I can do. I don't foresee a major change in the codebase to implement this.

**Comment by joshkopecek** [comment]
Done. v2.0.0 is out.

**Comment by markstos** [comment]
From the README, it appears the validation just got weaker. Here's an example of the new syntax:

```
  point: mongoose.Schema.Types.GeoJSON,
```

Before,  a point could be validated as a GeoJSON Point. Is the new syntax  looks like it would allow /any/ valid GeoJSON object to be used where only a point was expected. Is that the case? 

I was expecting a syntax more like one of these:

```
 point: mongoose.Schema.Types.GeoJSON.Point,
// OR
 point: mongoose.Schema.Types.GeoJSON({ type: Point })
```

In 2.0, how would specify that I wanted a field to be validated as GeoJSON Point?

**Comment by joshkopecek** [comment]
@markstos You're absolutely right. Too tired to notice that glaring omission.

Mongoose doesn't allow nested schemas, so I've readded the v1.0 types to the Types. I've kept the GeoJSON type in case anyone wants to be flexible about the type they're using.
